###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
  "idpedido": 1000,
  "descpedido": "Pedido pack de carnes",
  "preciopedido": 200000,
  "fechapedido": "05/07/23",
  "productospedido": "Carne de pollos, Carne de cerdo, Salchicha",
  "clientepedido": "Donde el cucho"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/64f1fec3ab58eb4a154b5fdb HTTP/1.1

###
DELETE http://localhost:9000/api/users/64f1fe46ab58eb4a154b5fd9 HTTP/1.1

###
PUT http://localhost:9000/api/users/64f1fe46ab58eb4a154b5fd9 HTTP/1.1
Content-Type: application/json

{
  "idpedido": 1000,
  "descpedido": "Pedido pack de carnes",
  "preciopedido": 200000,
  "fechapedido": "05/07/23",
  "productospedido": "Carne de pollos, Carne de cerdo, Salchicha",
  "clientepedido": "Donde el cuchox"
}